version: "3"

services:
  mysql:
    image: mysql:5
    container_name: mysql5
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    volumes:
      - ${MYSQL_DATA_DIR}:/var/lib/mysql
    restart: always
    networks:
      - drupal8

  drupal8:
    image: drupal:8
    container_name: drupal8
    ports:
      - "${DRUPAL_HTTP_PORT}:80"
    depends_on:
      - mysql
    volumes:
      - ${DRUPAL_MODULE_PATH}:/var/www/html/modules
      - ${DRUPAL_THEME_PATH}:/var/www/html/themes
    restart: always
    networks:
      - drupal8

networks:
  drupal8:
